name: eduscan_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  introduction_screen: ^3.1.17
  smooth_page_indicator: ^1.2.1
  camera: ^0.10.5+9
  path_provider: ^2.1.2
  path: ^1.9.0
  flutter_screenutil: ^5.9.3
  image_picker: ^1.1.2
  chat_bubbles: ^1.7.0
  file_picker: ^10.2.0
  flutter_sound: ^9.2.13
  permission_handler: ^11.3.1
  just_audio: ^0.9.36

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
